<?php

namespace IDPC\ContractualBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratoRepository extends EntityRepository {

    public function findContratosContratista($id) {

        $dql = 'SELECT c FROM IDPC\ContractualBundle\Entity\Contrato c
                JOIN c.estudio e
                WHERE e.contratista = :id';

        $query = $this->getEntityManager()
                ->createQuery($dql)
                ->setParameter('id', $id);
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
