<?php

namespace IDPC\ContractualBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagoRepository extends EntityRepository
{
    
        public function findPagosContratista($user) {

        $dql = 'SELECT p FROM IDPC\ContractualBundle\Entity\Pago p
                JOIN p.contrato c
                JOIN c.estudio e
                WHERE e.contratista = :user';

        $query = $this->getEntityManager()
                ->createQuery($dql)
                ->setParameter('user', $user);
        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
