<?php

namespace IDPC\ContractualBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SolicitudPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudPagoRepository extends EntityRepository
{
}
