<?php

namespace IDPC\SolicitudBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoplantaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoplantaRepository extends EntityRepository
{
}
