idpc_base:
    resource: "@IDPCBaseBundle/Resources/config/routing.yml"
    prefix:   /

_homepage:
    pattern:  /
    defaults: { _controller: IDPCContractualBundle:Pago:index }
    
idpc_contractual:
    resource: "@IDPCContractualBundle/Resources/config/routing.yml"
    prefix:   /

idpc_solicitud:
    resource: "@IDPCSolicitudBundle/Resources/config/routing.yml"
    prefix:   /

security_security:
    resource: "@SecuritySecurityBundle/Resources/config/routing.yml"
    prefix:   /

