<?php

namespace Security\SecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserDetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserDetRepository extends EntityRepository
{
}
