meissen_security_homepage:
    pattern:  /admin/
    defaults: { _controller: SecuritySecurityBundle:Default:index }
    
SecurityAnnotations:
    resource: "@SecuritySecurityBundle/Controller/"
    prefix:   /
    type:     annotation

    
