parameters:
#    security_security.example.class: Security\SecurityBundle\Example

services:
#    security_security.example:
#        class: %security_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
