<?php

namespace IDPC\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CdpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CdpRepository extends EntityRepository
{
}
