<?php

namespace IDPC\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProyectoInversionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoInversionRepository extends EntityRepository
{
}
