<?php

namespace IDPC\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoContratoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoContratoRepository extends EntityRepository
{
}
